function scenario = random_track()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.5 and Automated Driving System Toolbox 1.3.
% Generated on: 29-May-2019 10:31:05

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [99.9 179.5 0;
               158.3 181.3 0;
               185.2 136.5 0;
               124.2 96.6 0;
               184.7 70.1 0;
               150.2 31.5 0;
               14.3 35.5 0;
               62.3 92.5 0;
               22.3 132.4 0;
               31.3 179.5 0;
               99.9 179.5 0];
road(scenario, roadCenters);


