
clear all
close all
clc

track = createDrivingScenario()
plot(track),hold on
camroll(-90)

rb = roadBoundaries(track)

outerBoundary = rb{2};
innerBoundary = rb{1};
% figure
% plot(innerBoundary(:,1),innerBoundary(:,2),'b', outerBoundary(:,1),outerBoundary(:,2),'b'),grid on
% axis equal


xy = [ 30 50;
      80   60;
      89    100;
       0    1;
     ]
         
N = length(innerBoundary);
n_iterations = 4;

for i = 1:n_iterations
  position = [xy(i,1) xy(i,2)]';
  inside = track_constraints(position,N,innerBoundary,outerBoundary)
end

function inside_track = track_constraints(position,N,innerBoundary,outerBoundary)

x = position(1);
y = position(2);
inside_track = 0;

for i = 1:N
   j = N+1-i;
   innerPosition = [innerBoundary(i,1,1) innerBoundary(i,2,1)]';
   outerPosition = [outerBoundary(j,1,1) outerBoundary(j,2,1)]';
   
   if innerPosition(1)>outerPosition(1)
       x_out = innerPosition(1);
       x_in =  outerPosition(1);
   else
       x_out = outerPosition(1);
       x_in  = innerPosition(1);
   end
   
   if innerPosition(2)>outerPosition(2)
       y_out = innerPosition(2);
       y_in  = outerPosition(2);
   else
       y_out = outerPosition(2);
       y_in  = innerPosition(2);
   end

   if (x >= x_in && x <= x_out)
     if (y >= y_in && y <= y_out)
       inside_track = inside_track + 1;
     end
   end
end

if inside_track >= 1
    inside_track = 1;
else 
    inside_track = -1;
end

end

function scenario = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.5 and Automated Driving System Toolbox 1.3.
% Generated on: 09-Apr-2019 10:55:29

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [39.8 100.2 0;
    70 100.2 0;
    90.4 90.8 0;
    77.6 80.2 0;
    95 66.9 0;
    80.1 59.3 0;
    87.2 34.5 0;
    62.6 27.6 0;
    63.3 60.2 0;
    52.9 29.4 0;
    37.8 29.6 0;
    29 52.6 0;
    24.9 83.2 0;
    25.1 100.2 0;
    39.8 100.2 0];
road(scenario, roadCenters);
end


% https://www.mathworks.com/examples/automated-driving/mw/driving-ex94638429-driving-scenario-tutorial
