clear all
close all
clc

% create and plot track
track = createDrivingScenario()
plot(track),hold on
camroll(-90)

% find inner and outer boundaries coordinates
rb = roadBoundaries(track)
outerBoundary = rb{2};
innerBoundary = rb{1};

% figure
% plot(innerBoundary(:,1),innerBoundary(:,2),'b', outerBoundary(:,1),outerBoundary(:,2),'b'),grid on
% axis equal
        
N = length(innerBoundary);
n_iterations = N-1;

% plot of finish line and initialization the starting position
line([innerBoundary(2,1,1) outerBoundary(N,1,1)],[innerBoundary(2,2,1) outerBoundary(N,2,1)],'color','b','linewidth', 3) 
x   = [innerBoundary(1,1,1) outerBoundary(N,1,1)]';
y   = [innerBoundary(1,2,1) outerBoundary(N,2,1)]';
xy  = [mean(x) mean(y)]';

function scenario = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.5 and Automated Driving System Toolbox 1.3.
% Generated on: 10-Apr-2019 16:48:47

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [37.5 99.5 0;
    70.9 99.7 0;
    85.3 58.8 0;
    71.4 15.6 0;
    37.2 14.9 0;
    18.7 60.1 0;
    37.5 99.5 0];
road(scenario, roadCenters);
end