function scenario = random_track()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.5 and Automated Driving System Toolbox 1.3.
% Generated on: 29-Apr-2019 12:09:21

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [343 302 0;
    363 152 0;
    411 295 0;
    435 406 0;
    321 406 0;
    204 446 0;
    343 302 0];
road(scenario, roadCenters);

