function [fitresult, gof] = createFit(innerBoundary_x, innerBoundary_y)
%CREATEFIT(INNERBOUNDARY_X,INNERBOUNDARY_Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : innerBoundary_x
%      Y Output: innerBoundary_y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-May-2019 08:06:55


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( innerBoundary_x, innerBoundary_y );

% Set up fittype and options.
ft = fittype( 'poly2' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
h = plot( xData, yData );


