function scenario = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.5 and Automated Driving System Toolbox 1.3.
% Generated on: 19-Apr-2019 12:11:11

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [164 249.9 0;
    44 249.9 0;
    44 249.9 0;
    164 149.9 0;
    164 249.9 0];
road(scenario, roadCenters);

